#pragma once

#define INPUT_MOUSE_BUTTON_1         0
#define INPUT_MOUSE_BUTTON_2         1
#define INPUT_MOUSE_BUTTON_3         2
#define INPUT_MOUSE_BUTTON_4         3
#define INPUT_MOUSE_BUTTON_5         4
#define INPUT_MOUSE_BUTTON_6         5
#define INPUT_MOUSE_BUTTON_7         6
#define INPUT_MOUSE_BUTTON_8         7
#define INPUT_MOUSE_BUTTON_LAST      INPUT_MOUSE_BUTTON_8
#define INPUT_MOUSE_BUTTON_LEFT      INPUT_MOUSE_BUTTON_1
#define INPUT_MOUSE_BUTTON_RIGHT     INPUT_MOUSE_BUTTON_2
#define INPUT_MOUSE_BUTTON_MIDDLE    INPUT_MOUSE_BUTTON_3 
